name: passengers
description: A Flutter project for managing clients and users.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  image: ^4.1.3
  flutter_image_compress: ^2.0.4
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  corporation_no_icon: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700