// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZmzV8chrrILpmN9h8r9a27dV6X_g_FtU',
    appId: '1:615302580862:web:24816cce1f99c9c117662f',
    messagingSenderId: '615302580862',
    projectId: 'passengers-6a824',
    authDomain: 'passengers-6a824.firebaseapp.com',
    storageBucket: 'passengers-6a824.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN3pIJHxA9zIeoS-zI3-tbK2UoNy6qQMI',
    appId: '1:615302580862:android:6b5e48f58405b61e17662f',
    messagingSenderId: '615302580862',
    projectId: 'passengers-6a824',
    storageBucket: 'passengers-6a824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBmkKBsYjO7vofC2mBrmg48trODN2cfcA',
    appId: '1:615302580862:ios:a90b190112efbf1b17662f',
    messagingSenderId: '615302580862',
    projectId: 'passengers-6a824',
    storageBucket: 'passengers-6a824.firebasestorage.app',
    iosBundleId: 'com.example.passengers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBmkKBsYjO7vofC2mBrmg48trODN2cfcA',
    appId: '1:615302580862:ios:a90b190112efbf1b17662f',
    messagingSenderId: '615302580862',
    projectId: 'passengers-6a824',
    storageBucket: 'passengers-6a824.firebasestorage.app',
    iosBundleId: 'com.example.passengers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZmzV8chrrILpmN9h8r9a27dV6X_g_FtU',
    appId: '1:615302580862:web:7c30f84c4dad979b17662f',
    messagingSenderId: '615302580862',
    projectId: 'passengers-6a824',
    authDomain: 'passengers-6a824.firebaseapp.com',
    storageBucket: 'passengers-6a824.firebasestorage.app',
  );

}